import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getDatabase,ref,onValue,set}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js";
import{getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import{firebaseConfig}from"./firebase-config.js";
const app=initializeApp(firebaseConfig),db=getDatabase(app),auth=getAuth(app),dbref=ref(db,"tournament");
const R={r1:20,r2:10,r3:5,r4:2,r5:1}, names=["ROUND 1","ROUND 2","ROUND 3","SEMIFINAL","FINAL"];let s;
const blank=()=>({title:"Turnamen PD AMPG Banten",teams:Array.from({length:20},(_,i)=>"PAIR "+(i+1)),matches:Object.fromEntries(Object.entries(R).map(([r,n])=>[r,Array.from({length:n},()=>({sa:"",sb:"",winner:null}))])),updatedAt:null});
function norm(x){let a=x||blank();a.teams=Array.from({length:20},(_,i)=>a.teams?.[i]||"PAIR "+(i+1));for(let[r,n]of Object.entries(R))a.matches[r]=Array.from({length:n},(_,i)=>({...((a.matches||{})[r]?.[i]||{sa:"",sb:"",winner:null})}));return a}
function pname(r,i,side){if(r==="r1")return s.teams[i*2+(side==="a"?0:1)];let p={r2:"r1",r3:"r2",r4:"r3",r5:"r4"}[r],m=i*2+(side==="a"?0:1),w=s.matches[p][m]?.winner;if(!w)return"—";return pname(p,m,w)}
function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function render(){document.querySelector("#title").textContent=s.title;document.querySelector("#updated").textContent=s.updatedAt?"Terakhir diperbarui: "+new Date(s.updatedAt).toLocaleString("id-ID"):"Belum ada pembaruan.";document.querySelector("#bracket").innerHTML=names.map((n,k)=>{let r=Object.keys(R)[k];return `<section class="round"><h3>${n}</h3><div class="matches">${s.matches[r].map((m,i)=>{let a=pname(r,i,"a"),b=pname(r,i,"b");return `<article class="match"><div class="meta">Match ${i+1}</div><div class="team ${m.winner==="a"?"win":""}"><span class="${a==="—"?"empty":""}">${esc(a)}</span><b>${esc(m.sa)}</b></div><div class="team ${m.winner==="b"?"win":""}"><span class="${b==="—"?"empty":""}">${esc(b)}</span><b>${esc(m.sb)}</b></div></article>`}).join("")}</div></section>`}).join("")}
function adminRender(){titleInput.value=s.title;teams.innerHTML=s.teams.map((x,i)=>`<div class="teamedit"><b>${i+1}</b><input data-team="${i}" value="${esc(x)}"></div>`).join("");let h="";for(let[r,n]of Object.entries(R))for(let i=0;i<n;i++){let m=s.matches[r][i],a=pname(r,i,"a"),b=pname(r,i,"b");h+=`<div class="editor"><b>${r.toUpperCase()} — Match ${i+1}</b><div class="row"><span>${esc(a)}</span><input data-score="${r}.${i}.sa" value="${esc(m.sa)}" placeholder="Skor"></div><div class="row"><span>${esc(b)}</span><input data-score="${r}.${i}.sb" value="${esc(m.sb)}" placeholder="Skor"></div><select data-winner="${r}.${i}"><option value="">Belum dipilih</option><option value="a" ${m.winner==="a"?"selected":""}>${esc(a)}</option><option value="b" ${m.winner==="b"?"selected":""}>${esc(b)}</option></select></div>`}matches.innerHTML=h}
onValue(dbref,x=>{s=norm(x.val());render();if(auth.currentUser)adminRender();status.textContent="● LIVE";status.className="online"});
loginBtn.onclick=async()=>{error.textContent="";try{await signInWithEmailAndPassword(auth,email.value,password.value)}catch(e){error.textContent="Login gagal. Periksa email/password Firebase."}};
logout.onclick=()=>signOut(auth);
adminBtn.onclick=()=>modal.classList.remove("hidden");close.onclick=()=>modal.classList.add("hidden");
onAuthStateChanged(u=>{login.classList.toggle("hidden",!!u);admin.classList.toggle("hidden",!u);if(u)adminRender()});
save.onclick=async()=>{let n=norm(s);n.title=titleInput.value.trim()||"Turnamen PD AMPG Banten";document.querySelectorAll("[data-team]").forEach(e=>n.teams[+e.dataset.team]=e.value.trim()||"PAIR "+(+e.dataset.team+1));document.querySelectorAll("[data-score]").forEach(e=>{let[r,i,k]=e.dataset.score.split(".");n.matches[r][+i][k]=e.value});document.querySelectorAll("[data-winner]").forEach(e=>{let[r,i]=e.dataset.winner.split(".");n.matches[r][+i].winner=e.value||null});n.updatedAt=Date.now();await set(dbref,n);message.textContent="Tersimpan — publik langsung melihat perubahan.";setTimeout(()=>message.textContent="",3000)};
reset.onclick=async()=>{if(confirm("Reset seluruh bracket?"))await set(dbref,{...blank(),updatedAt:Date.now()})};